wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.9
    start_time: 1720100580
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 19
      4: 3.11.9
      5: 0.12.16
      8:
      - 1
      - 3
      - 5
learning_rate:
  desc: null
  value: 0.02
learning_rates:
  desc: null
  value:
  - 0.02
  - 0.2
  - 0.3
  - 0.4
loss_function:
  desc: null
  value: log_loss
loss_functions:
  desc: null
  value:
  - log_loss
max_depth:
  desc: null
  value: 4
max_depths:
  desc: null
  value:
  - 4
  - 5
  - 6
  - 7
min_samples_leaf:
  desc: null
  value: 2
min_samples_leafs:
  desc: null
  value:
  - 1
  - 2
min_samples_split:
  desc: null
  value: 4
min_samples_splits:
  desc: null
  value:
  - 2
  - 4
n_estimators:
  desc: null
  value: 120
subsample:
  desc: null
  value: 0.7
subsamples:
  desc: null
  value:
  - 0.7
  - 1.0
